name: Deployment

on: push

jobs:
  create_storybook_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'

      - name: Retrieve the cached main "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache-main
        with:
          path: node_modules
          key: node-modules-main-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      
      - name: Install main dependencies (if the cached directory was not found)
        if: steps.node-cache-main.outputs.cache-hit != 'true'
        run: npm ci

      - name: Create the static pages directory locally in CI
        run: npm run build-storybook

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./storybook-static/